#!/bin/sh

# Prepend the current branch name to the commit message
BRANCH_NAME=`git symbolic-ref --short HEAD`
if [ -n "$BRANCH_NAME" ]; then
  # using '#' as safe delimeter since the branch name often contains '/'
  sed -i.bak -e "1s#^#$BRANCH_NAME: #" $1
fi
echo >> "$1"

# Add a signature block to the commit
SOB=$(git var GIT_AUTHOR_IDENT | sed -n 's/^\(.*>\).*$/Signed-off-by: \1/p')
grep -qs "^$SOB" "$1" || echo "$SOB" >> "$1"
